package com.atlassian.confluence.extra.jira.api.services;

import com.atlassian.confluence.content.render.xhtml.ConversionContext;
import com.atlassian.confluence.extra.jira.model.JiraResponseData;
import com.atlassian.confluence.xhtml.api.MacroDefinition;

import java.util.List;
import java.util.Set;

/**
 * Service responsible for sending batch request to a JIRA server and get the results.
 */
public interface AsyncJiraIssueBatchService
{

    /**
     * <p>This method aims to process requests by server id, transform retrieved data to html.</p>
     *
     * @param clientId                  the key used to store data
     * @param serverId                 JIRA server ID
     * @param keys                     list of issue's keys to query data from Jira
     * @param macroDefinitions         list of macro definitions used while transforming retrieved data to html
     * @param conversionContext        conversion context used while transforming retrieved data to html
     */
    void processRequest(String clientId, String serverId, Set<String> keys, List<MacroDefinition> macroDefinitions, ConversionContext conversionContext);

    /**
     * <p>Retrieve data generated by {@link #processRequest}.</p>
     *
     * @param clientId the key used to retrieve data
     * @return response data (which has been transform to html) from Jira
     * @throws Exception
     */
    JiraResponseData getAsyncJiraResults(String clientId) throws Exception;
}
